name: event_listener
description:  A dart package implements NodeJS style event listening functionality
version: 0.1.6
homepage: https://github.com/behemehal/event_listener
repository: https://github.com/behemehal/event_listener

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.19.4
  http: any