name: event_listener
description:  A dart package implements NodeJS style event listening functionality
version: 0.1.1
homepage: https://github.com/behemehal/event_listener
repository: https://github.com/behemehal/event_listener

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: 1.16.0-nullsafety.13
  http: any
