version: 2
jobs:
  build:    
    docker:
      - image: google/dart:2.9.1
    branches:
      only: master
    steps:
      - checkout
      - run:
          name: Run the application tests
          command: dart test